### ISSUE TITLE
油价数据怎么来的 

### ISSUE THREAD

**Issue by XinJiangQingMang** [zzlphp/-lite#1]

**Comment by zzlphp** [comment]
第三方api提供的数据
Showapi 可以关注下

**Comment by XinJiangQingMang** [comment]
我测试了  跟你的结果好像不一样 只要你的小程序的油价是更新的 别的 都不更新

**Comment by XinJiangQingMang** [comment]
所有的api平台我都测了一遍  只有你的数据实时是符合本地价格的

**Comment by XinJiangQingMang** [comment]
![image](https://user-images.githubusercontent.com/19700237/39692406-5a9a3a72-5213-11e8-83da-4e7eaa5a2d99.png)
ta他这个显示的6.66 明显是错的  你的小程序的数据是  6.95 是对的

**Comment by mcmf** [comment]
6475813  我qq 或者baidu748 微信加个联系方式 ？ #

**Comment by zzlphp** [comment]
已经加你好友了
